title: The SkyBoat
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5234738918952644
  brandStrength: 0.5625
  rhythmicContrast: 0.5
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  lightness: 0.5625
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: SkyBoat
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.28631
layout_spectrum: 0.8851064
