name: SkyBoat
favicon: null
layout_spectrum: 0.76962
typography_spectrum: 0.28631
title: The SkyBoat
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.5234738918952644
  rhythmicContrast: 0.5
purpose: []
